### ISSUE TITLE
error with h5ads from AnnData version 0.8.0 

### ISSUE THREAD

**Issue by iolosquires** [haniffalab/vitessce-pipeline#41]
If the h5ad file has been made with most recent AnnData version 0.8.0, then it won't run in the pipeline. I tried to do this and got the error:

KeyError: 'dict'
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/Users/iolosquires/sci-spatial-data/bin/router.py", line 20, in <module>
      fire.Fire(main)
    File "/usr/local/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
      component_trace = _Fire(component, args, parsed_flag_args, context, name)
    File "/usr/local/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
      component, remaining_args = _CallAndUpdateTrace(
    File "/usr/local/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
      component = fn(*varargs, **kwargs)
    File "/Users/iolosquires/sci-spatial-data/bin/router.py", line 13, in main
      out_file = h5ad_to_zarr(file=file_path, stem=stem, **args)
    File "/Users/iolosquires/sci-spatial-data/bin/process_h5ad.py", line 22, in h5ad_to_zarr
      adata = ad.read(file)
    File "/usr/local/lib/python3.9/site-packages/anndata/_io/h5ad.py", line 421, in read_h5ad
      d[k] = read_attribute(f[k])
    File "/usr/local/lib/python3.9/functools.py", line 888, in wrapper
      return dispatch(args[0].__class__)(*args, **kw)
    File "/usr/local/lib/python3.9/site-packages/anndata/_io/utils.py", line 183, in func_wrapper
      raise AnnDataReadError(
  anndata._io.utils.AnnDataReadError: Above error raised while reading key '/layers' of type <class 'h5py._hl.group.Group'> from /.

I think the pipeline requires the h5ad file to have been made using anndata version 0.7.8

**Comment by BioinfoTongLI** [comment]
Thanks @iolosquires , indeed it requires 0.7.8 as stated in https://github.com/haniffalab/sci-spatial-data/blob/dev/docker/Dockerfile.router#L10. 
May I ask how the h5ad was generated? from spaceranger or ?

**Comment by iolosquires** [comment]
Hi Tong, sorry for my slow response. I believe it is from space ranger. If I open the h5ad. file and do "data.obs.keys" then each spot_id begins "space ranger..."

**Comment by BioinfoTongLI** [comment]
Np! - Ok, I see. Thanks for the info! Actually the pipeline now can also load raw space ranger output and convert to h5ads as well (so that we can be sure about anndata version). But that's not thoroughly tested. I'll add the docs for that once it's done.

**Comment by davehorsfall** [comment]
@dannda closed c2362c88f0f00eba519bb259970689f5f98f5410
